<a href="https://colab.research.google.com/github/JulioBT07/Regresi-n-Logistica/blob/main/Actividad_7_(Regresi%C3%B3n_Log%C3%ADstica).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Agregar el archivo: “Cuentas_credicel.csv”

In [1677]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [1678]:
df = pd.read_csv('cuentas_credicel.csv', encoding='latin1')
df

<ipython-input-1678-0007bc6baa22>:1: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('cuentas_credicel.csv', encoding='latin1')


folio       tag  folio_solicitud           fecha     marca                        modelo plazo  precio  enganche  descuento  semana  monto_financiado  costo_total  monto_accesorios                      agente_venta dis_venta  status  fraude      empresa  inversion  pagos_realizados  reautorizacion fecha_ultimo_pago fecha_pago_proximo status_cuenta  puntos  riesgo  score_buro razones_buro  porc_eng limite_credito  semana_actual cp_cliente  edad_cliente                   cd_cliente edo_cliente                     cd_venta            edo_venta                curp
0          3  HDNAWQ3A               30  12/11/21 19:00       ZTE            Blade A3 2020 RO B   26S  1949.0     780.0        0.0      81            1169.0         2106               0.0   Sintia Verenice Tenorio Perez E   mic0437       2       0     microtec          0                 0               0               NaN                NaN           NaN       0    0.00           0          NaN     40.02           5000             26        NaN          23.0                            0           0                    Tantoyuca             Veracruz  AEVM980413MVZNDR02
1          4  M418YNR4               33  12/11/21 19:15  MOTOROLA  LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0        0.0     225            1949.0         2925               0.0             Alvaro Rafael Pascual    mic015       2       0     microtec          0                 0               0               NaN                NaN           NaN       0    0.00           0          NaN     35.01           6000             13        NaN          60.0                      PUEBLA         PUE.   Heroica Puebla de Zaragoza               Puebla  ZALC610119MPLPRR07
2          5  SZ7V3NZT               37  13/11/21 14:13       ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0     170            1469.0         2210               0.0   Sintia Verenice Tenorio Perez E   mic0437       3       0     microtec          0                 0               0               NaN                NaN     Cancelado       0    0.00           0          NaN     25.01              0             74        NaN          58.0                    TANTOYUCA        VER.                            0                    0                   0
3          6  9I08UIQZ               38  13/11/21 15:45       ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0     170            1469.0         2210               0.0        Luz Aylin Hernandez Lopez1   mic0748       2       0     microtec          0                 0               0               NaN                NaN           NaN       0    0.00           0          NaN     25.01           7000             13        NaN          42.0                  AMXTLAN PUE         NaN                     Zacatlan               Puebla  SAMJ790115MPLNRS02
4          7  JMF4LKYU               44  13/11/21 16:10  MOTOROLA                         G10 B   39S  4299.0    1075.0        0.0     178            3224.0         6942               0.0   Sintia Verenice Tenorio Perez E   mic0437       1       0     microtec          0                 0               0     05/03/22 0:00      12/03/22 0:00          Mora       0    0.00           0          NaN     25.01           7000             74        NaN          33.0                   TANTOYUCA         VER.                    Tantoyuca             Veracruz  TEHF880707HVZRRR07
...      ...       ...              ...             ...       ...                           ...   ...     ...       ...        ...     ...               ...          ...               ...                               ...       ...     ...     ...          ...        ...               ...             ...               ...                ...           ...     ...     ...         ...          ...       ...            ...            ...        ...           ...                          ...         ...                          ...                  ...          

In [1679]:
np.unique(df['status'])

array([1, 2, 3, 4])

In [1680]:
np.unique(df['fraude'])

array([0, 1])

In [1681]:
df['fraude'].value_counts()

0    21034
1     1701
Name: fraude, dtype: int64

In [1682]:
df['inversion'].value_counts()

0    17356
1     5379
Name: inversion, dtype: int64

In [1683]:
df['pagos_realizados'].value_counts()

0     4461
13    1277
1     1091
12    1072
2     1003
3      971
4      927
5      825
6      810
11     782
7      728
9      728
8      718
10     698
14     697
15     525
16     458
26     425
17     386
27     369
18     358
25     352
19     336
20     293
22     276
21     268
24     265
23     264
28     185
29     169
30     147
31     101
33      90
37      87
35      76
32      75
38      72
34      71
40      64
39      60
36      55
41      44
42      23
43      11
44      10
46       7
45       5
48       4
49       4
53       4
51       3
60       1
57       1
47       1
62       1
52       1
Name: pagos_realizados, dtype: int64

In [1684]:
df['reautorizacion'].value_counts()

0    21961
1      774
Name: reautorizacion, dtype: int64

In [1685]:
df['marca'].value_counts()

Samsung         8991
SAMSUNG         3524
MOTOROLA        3078
ZTE             1948
Motorola        1658
NOKIA           1121
TECNO MOBILE     833
Hisense          371
HISENSE          270
Nokia            262
ALCATEL          215
TCL              113
Alcatel          101
Lanix             90
VIVO              60
Vivo              45
LG                20
WIKO               9
NYX                7
B2M                4
KODAK              3
RT                 3
LANIX              2
INCO               2
Huawei             1
SENWA              1
alcatel            1
Senwa              1
TECHPAD            1
Name: marca, dtype: int64

In [1686]:
df['empresa'].value_counts()

microtec             9310
servicel             7348
comunicatec          1020
procredito            697
phonepay              456
texpress              396
centrocel             395
apartacel             324
yaavs                 258
aespinosa             221
leket                 186
compercel             174
linetelc              172
arcelular             171
telesystems           156
crglobal              153
grupoph               136
redworld              126
pixelulares           112
emnagar                81
phuny                  80
drmedia                73
quality                71
tucelya                65
maifon                 60
todocell               52
mistraltechnology      48
financel               46
fixmobile              43
alessan                39
satelitel              36
ahorrocelsonora        35
signumaxis             35
ccelular               32
phoneone               24
laragrajales           24
egocomunicaciones      15
martz                  14
teknosmart  

In [1687]:
df['status_cuenta'].value_counts()

Corriente    10014
Mora          4604
Atraso        2960
Fraude        1696
Cancelado      147
Name: status_cuenta, dtype: int64

In [1688]:
df['puntos'].value_counts()

 12    3918
 11    3786
 0     3248
 13    2760
 9     1418
 10    1357
 14    1230
 32     579
 48     525
 15     426
 31     381
 47     352
 8      235
 16     182
 45     147
 7      140
 30     140
 29     136
 28     132
 27     125
 44     120
 26      93
 39      78
 25      77
 40      76
 43      75
 46      75
 42      71
 36      70
 20      68
 41      68
 24      67
 37      62
 23      59
 17      58
 38      56
 22      56
 21      56
 34      44
 18      41
 19      37
 35      29
 33      20
 6       14
 5       14
 4        7
 2        6
 3        4
-15       3
 50       3
 1        2
-4        2
-11       1
-8        1
-1        1
-2        1
-12       1
-5        1
-3        1
Name: puntos, dtype: int64

In [1689]:
df['puntos'].describe()

count    22735.000000
mean        14.156807
std         11.399142
min        -15.000000
25%         10.000000
50%         12.000000
75%         14.000000
max         50.000000
Name: puntos, dtype: float64

In [1690]:
df['edo_venta'].value_counts()

Puebla                  6639
Yucatan                 5660
Veracruz                3795
Guerrero                2215
Oaxaca                   653
Campeche                 596
Tabasco                  522
Quintana Roo             498
Baja California Sur      451
Tlaxcala                 308
San Luis Potosi          217
Chiapas                  187
0                        119
Hidalgo                  114
Sonora                   104
Guanajuato                94
Jalisco                   94
Coahuila De Zaragoza      86
Morelos                   85
Aguascalientes            71
Estado De Mexico          67
Nuevo Leon                63
Queretaro                 21
Michoacan                 20
Sinaloa                   16
Chihuahua                 15
Durango                   13
Zacatecas                  7
Baja California            5
Name: edo_venta, dtype: int64

In [1691]:
df['razones_buro'].value_counts()

C2             2422
K0,J0,E2,D8     620
C4              529
C1              502
K0,J0,E2,M1     355
               ... 
G1,E4,E0,J0       1
J0,P6,F7,E2       1
D2,J0,E2,P6       1
E0,J0,E2,         1
E2,E0,J0,P6       1
Name: razones_buro, Length: 1000, dtype: int64

##Realiza las acciones de preprocesamiento necesarias: Nulos y Outliers

In [1692]:
df1 =df.fillna(method="bfill")
df1.isnull().sum()

folio                  0
tag                    0
folio_solicitud        0
fecha                  0
marca                  0
modelo                 0
plazo                  0
precio                 0
enganche               0
descuento              0
semana                 0
monto_financiado       0
costo_total            0
monto_accesorios       0
agente_venta           0
dis_venta              0
status                 0
fraude                 0
empresa                0
inversion              0
pagos_realizados       0
reautorizacion         0
fecha_ultimo_pago      0
fecha_pago_proximo     0
status_cuenta         35
puntos                 0
riesgo                 0
score_buro             0
razones_buro           0
porc_eng               0
limite_credito         0
semana_actual          0
cp_cliente             0
edad_cliente           0
cd_cliente             0
edo_cliente            0
cd_venta               0
edo_venta              0
curp                   0
dtype: int64

In [1693]:
df1 = df1.fillna(method="ffill")
df1.isnull().sum()

folio                 0
tag                   0
folio_solicitud       0
fecha                 0
marca                 0
modelo                0
plazo                 0
precio                0
enganche              0
descuento             0
semana                0
monto_financiado      0
costo_total           0
monto_accesorios      0
agente_venta          0
dis_venta             0
status                0
fraude                0
empresa               0
inversion             0
pagos_realizados      0
reautorizacion        0
fecha_ultimo_pago     0
fecha_pago_proximo    0
status_cuenta         0
puntos                0
riesgo                0
score_buro            0
razones_buro          0
porc_eng              0
limite_credito        0
semana_actual         0
cp_cliente            0
edad_cliente          0
cd_cliente            0
edo_cliente           0
cd_venta              0
edo_venta             0
curp                  0
dtype: int64

In [1694]:
df1.isnull().sum().sum()

0

In [1695]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22735 entries, 0 to 22734
Data columns (total 39 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   folio               22735 non-null  int64  
 1   tag                 22735 non-null  object 
 2   folio_solicitud     22735 non-null  int64  
 3   fecha               22735 non-null  object 
 4   marca               22735 non-null  object 
 5   modelo              22735 non-null  object 
 6   plazo               22735 non-null  object 
 7   precio              22735 non-null  float64
 8   enganche            22735 non-null  float64
 9   descuento           22735 non-null  float64
 10  semana              22735 non-null  int64  
 11  monto_financiado    22735 non-null  float64
 12  costo_total         22735 non-null  int64  
 13  monto_accesorios    22735 non-null  float64
 14  agente_venta        22735 non-null  object 
 15  dis_venta           22735 non-null  object 
 16  stat

##Convertir las variables que sean necesarias en variables de tipo  dicotómica con las categorías que se consideren pertinentes, aplicando la herramienta de  “Regresión Logística”

In [1696]:
df1['limite_credito'] = pd.to_numeric(df1['limite_credito'], errors='coerce')
df1['limite_credito'].fillna(7000, inplace=True)

In [1697]:
df_1 = df1.copy()
df_1['status_cuenta_dicotomica'] = df1['status_cuenta'].apply(lambda x: 1 if 'Corriente' in x else 0)
df_1['puntos'] = (df1['puntos'] > 30).astype(int)

In [1698]:
df_1['status_cuenta_dicotomica'].value_counts()

0    11812
1    10923
Name: status_cuenta_dicotomica, dtype: int64

In [1699]:
df_1['puntos'].value_counts()

0    19904
1     2831
Name: puntos, dtype: int64

In [1700]:
df_1

folio       tag  folio_solicitud           fecha     marca                        modelo plazo  precio  enganche  descuento  semana  monto_financiado  costo_total  monto_accesorios                      agente_venta dis_venta  status  fraude      empresa  inversion  pagos_realizados  reautorizacion fecha_ultimo_pago fecha_pago_proximo status_cuenta  puntos  riesgo  score_buro razones_buro  porc_eng  limite_credito  semana_actual cp_cliente  edad_cliente                   cd_cliente edo_cliente                     cd_venta            edo_venta                curp  status_cuenta_dicotomica
0          3  HDNAWQ3A               30  12/11/21 19:00       ZTE            Blade A3 2020 RO B   26S  1949.0     780.0        0.0      81            1169.0         2106               0.0   Sintia Verenice Tenorio Perez E   mic0437       2       0     microtec          0                 0               0     05/03/22 0:00      12/03/22 0:00     Cancelado       0    0.00           0           C1     40.02          5000.0             26      72490          23.0                            0           0                    Tantoyuca             Veracruz  AEVM980413MVZNDR02                         0
1          4  M418YNR4               33  12/11/21 19:15  MOTOROLA  LTE XT2097-12 E7I POWER Azul   13S  2999.0    1050.0        0.0     225            1949.0         2925               0.0             Alvaro Rafael Pascual    mic015       2       0     microtec          0                 0               0     05/03/22 0:00      12/03/22 0:00     Cancelado       0    0.00           0           C1     35.01          6000.0             13      72490          60.0                      PUEBLA         PUE.   Heroica Puebla de Zaragoza               Puebla  ZALC610119MPLPRR07                         0
2          5  SZ7V3NZT               37  13/11/21 14:13       ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0     170            1469.0         2210               0.0   Sintia Verenice Tenorio Perez E   mic0437       3       0     microtec          0                 0               0     05/03/22 0:00      12/03/22 0:00     Cancelado       0    0.00           0           C1     25.01             0.0             74      72490          58.0                    TANTOYUCA        VER.                            0                    0                   0                         0
3          6  9I08UIQZ               38  13/11/21 15:45       ZTE            BLADE A3 2020 Gris   13S  1959.0     490.0        0.0     170            1469.0         2210               0.0        Luz Aylin Hernandez Lopez1   mic0748       2       0     microtec          0                 0               0     05/03/22 0:00      12/03/22 0:00          Mora       0    0.00           0           C1     25.01          7000.0             13      72490          42.0                  AMXTLAN PUE        VER.                     Zacatlan               Puebla  SAMJ790115MPLNRS02                         0
4          7  JMF4LKYU               44  13/11/21 16:10  MOTOROLA                         G10 B   39S  4299.0    1075.0        0.0     178            3224.0         6942               0.0   Sintia Verenice Tenorio Perez E   mic0437       1       0     microtec          0                 0               0     05/03/22 0:00      12/03/22 0:00          Mora       0    0.00           0           C1     25.01          7000.0             74      72490          33.0                   TANTOYUCA         VER.                    Tantoyuca             Veracruz  TEHF880707HVZRRR07                         0
...      ...       ...              ...             ...       ...                           ...   ...     ...       ...        ...     ...               ...          ...               ...                               ...       ...     ...     ...          ...        ...               ...             ...               ...                ...           ...     ...     ...         ...          ...    

##Outilers

In [1701]:
df1_numeric = df_1.select_dtypes(include=['number'])
categoric_columns = df_1.select_dtypes(include=['object'])

In [1702]:
df1_numeric

folio  folio_solicitud  precio  enganche  descuento  semana  monto_financiado  costo_total  monto_accesorios  status  fraude  inversion  pagos_realizados  reautorizacion  puntos  riesgo  score_buro  porc_eng  limite_credito  semana_actual  edad_cliente  status_cuenta_dicotomica
0          3               30  1949.0     780.0        0.0      81            1169.0         2106               0.0       2       0          0                 0               0       0    0.00           0     40.02          5000.0             26          23.0                         0
1          4               33  2999.0    1050.0        0.0     225            1949.0         2925               0.0       2       0          0                 0               0       0    0.00           0     35.01          6000.0             13          60.0                         0
2          5               37  1959.0     490.0        0.0     170            1469.0         2210               0.0       3       0          0                 0               0       0    0.00           0     25.01             0.0             74          58.0                         0
3          6               38  1959.0     490.0        0.0     170            1469.0         2210               0.0       2       0          0                 0               0       0    0.00           0     25.01          7000.0             13          42.0                         0
4          7               44  4299.0    1075.0        0.0     178            3224.0         6942               0.0       1       0          0                 0               0       0    0.00           0     25.01          7000.0             74          33.0                         0
...      ...              ...     ...       ...        ...     ...               ...          ...               ...     ...     ...        ...               ...             ...     ...     ...         ...       ...             ...            ...           ...                       ...
22730  22967            96502  3349.0     297.0        0.0     211            3052.0         5486               0.0       1       0          0                 0               0       0   27.40         469      8.87         10000.0              0          22.0                         0
22731  22968            96479  4100.0    1209.0        0.0     200            2891.0         5200               0.0       1       0          0                 0               0       0   19.00         502     29.49          5000.0              0          27.0                         0
22732  22969            96442  4849.0    1152.0        0.0     256            3697.0         6656               0.0       1       0          0                 0               0       0   26.65         459     23.76          4750.0              0          36.0                         0
22733  22970            96536  9799.0    2799.0        0.0     386            7000.0        15054               0.0       1       0          0                 0               0       0  -17.35         699     28.56          7000.0              0          53.0                         0
22734  22971            96534  5399.0    1086.0        0.0     299            4313.0         7774               0.0       1       0          1                 0               0       0   21.80           0     20.11          4750.0              0          19.0                         0

[22735 rows x 22 columns]

In [1703]:
df1_numeric['reautorizacion'].value_counts()

0    21961
1      774
Name: reautorizacion, dtype: int64

In [1704]:
y=df1_numeric
Limite_Superior= y.mean() + 3*y.std()
Limite_Inferior= y.mean() - 3*y.std()
print("Limite superior permitido", Limite_Superior)
print("Limite inferior permitido", Limite_Inferior)

Limite superior permitido folio                        31323.107698
folio_solicitud             127723.906961
precio                        8081.558082
enganche                      2356.496845
descuento                      478.215020
semana                         541.287392
monto_financiado              6366.317810
costo_total                  12857.588246
monto_accesorios               191.260880
status                           2.611178
fraude                           0.864131
inversion                        1.511599
pagos_realizados                39.306132
reautorizacion                   0.578086
puntos                           1.115071
riesgo                          58.456322
score_buro                    1142.021000
porc_eng                        45.711306
limite_credito               12330.101115
semana_actual                   64.380898
edad_cliente                   422.314014
status_cuenta_dicotomica         1.979334
dtype: float64
Limite inferior permitido folio    

In [1705]:
# Crear una lista de columnas a excluir
columnas_excluir = ['reautorizacion', 'inversion', 'fraude']
# Filtrar los datos
data = df1_numeric.copy()
for columna in columnas_excluir:
    data[columna] = y[columna]

data = data[(y <= Limite_Superior) & (y >= Limite_Inferior)]
columnas_excluidas = df1_numeric[columnas_excluir]

# Filtrar los datos
data = df1_numeric.copy()
data = data[(y <= Limite_Superior) & (y >= Limite_Inferior)]

# Agregar las columnas excluidas de nuevo
for columna in columnas_excluir:
    data[columna] = columnas_excluidas[columna]

In [1706]:
data['reautorizacion'].value_counts()

0    21961
1      774
Name: reautorizacion, dtype: int64

In [1707]:
data

folio  folio_solicitud  precio  enganche  descuento  semana  monto_financiado  costo_total  monto_accesorios  status  fraude  inversion  pagos_realizados  reautorizacion  puntos  riesgo  score_buro  porc_eng  limite_credito  semana_actual  edad_cliente  status_cuenta_dicotomica
0          3               30  1949.0     780.0        0.0    81.0            1169.0       2106.0               0.0     2.0       0          0               0.0               0       0    0.00           0     40.02          5000.0           26.0          23.0                         0
1          4               33  2999.0    1050.0        0.0   225.0            1949.0       2925.0               0.0     2.0       0          0               0.0               0       0    0.00           0     35.01          6000.0           13.0          60.0                         0
2          5               37  1959.0     490.0        0.0   170.0            1469.0       2210.0               0.0     NaN       0          0               0.0               0       0    0.00           0     25.01             0.0            NaN          58.0                         0
3          6               38  1959.0     490.0        0.0   170.0            1469.0       2210.0               0.0     2.0       0          0               0.0               0       0    0.00           0     25.01          7000.0           13.0          42.0                         0
4          7               44  4299.0    1075.0        0.0   178.0            3224.0       6942.0               0.0     1.0       0          0               0.0               0       0    0.00           0     25.01          7000.0            NaN          33.0                         0
...      ...              ...     ...       ...        ...     ...               ...          ...               ...     ...     ...        ...               ...             ...     ...     ...         ...       ...             ...            ...           ...                       ...
22730  22967            96502  3349.0     297.0        0.0   211.0            3052.0       5486.0               0.0     1.0       0          0               0.0               0       0   27.40         469      8.87         10000.0            0.0          22.0                         0
22731  22968            96479  4100.0    1209.0        0.0   200.0            2891.0       5200.0               0.0     1.0       0          0               0.0               0       0   19.00         502     29.49          5000.0            0.0          27.0                         0
22732  22969            96442  4849.0    1152.0        0.0   256.0            3697.0       6656.0               0.0     1.0       0          0               0.0               0       0   26.65         459     23.76          4750.0            0.0          36.0                         0
22733  22970            96536     NaN       NaN        0.0   386.0               NaN          NaN               0.0     1.0       0          0               0.0               0       0  -17.35         699     28.56          7000.0            0.0          53.0                         0
22734  22971            96534  5399.0    1086.0        0.0   299.0            4313.0       7774.0               0.0     1.0       0          1               0.0               0       0   21.80           0     20.11          4750.0            0.0          19.0                         0

[22735 rows x 22 columns]

In [1708]:
res = pd.concat([data, categoric_columns], axis = 1)
data_clean=res.copy()
moda_columns = ['status', 'fraude', 'inversion', 'pagos_realizados', 'reautorizacion', 'marca', 'empresa', 'status_cuenta', 'puntos', 'razones_buro']
moda_valores = data_clean[moda_columns].mode().iloc[0]

# Calcular el promedio para las demás columnas
promedio_valores = data_clean.drop(moda_columns, axis=1).mean()
# Llenar los valores nulos con la moda para las columnas específicas
data_clean[moda_columns] = data_clean[moda_columns].fillna(moda_valores)
# Llenar los valores nulos con el promedio para las demás columnas
data_clean = data_clean.fillna(promedio_valores)
data_clean

<ipython-input-1708-035c3f9086c7>:7: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  promedio_valores = data_clean.drop(moda_columns, axis=1).mean()


folio  folio_solicitud       precio    enganche  descuento  semana  monto_financiado  costo_total  monto_accesorios  status  fraude  inversion  pagos_realizados  reautorizacion  puntos  riesgo  score_buro  porc_eng  limite_credito  semana_actual  edad_cliente  status_cuenta_dicotomica       tag           fecha     marca                        modelo plazo                      agente_venta dis_venta      empresa fecha_ultimo_pago fecha_pago_proximo status_cuenta razones_buro cp_cliente                   cd_cliente edo_cliente                     cd_venta            edo_venta                curp
0          3               30  1949.000000   780.00000        0.0    81.0        1169.00000  2106.000000               0.0     2.0       0          0               0.0               0       0    0.00           0     40.02          5000.0      26.000000          23.0                         0  HDNAWQ3A  12/11/21 19:00       ZTE            Blade A3 2020 RO B   26S   Sintia Verenice Tenorio Perez E   mic0437     microtec     05/03/22 0:00      12/03/22 0:00     Cancelado           C1      72490                            0           0                    Tantoyuca             Veracruz  AEVM980413MVZNDR02
1          4               33  2999.000000  1050.00000        0.0   225.0        1949.00000  2925.000000               0.0     2.0       0          0               0.0               0       0    0.00           0     35.01          6000.0      13.000000          60.0                         0  M418YNR4  12/11/21 19:15  MOTOROLA  LTE XT2097-12 E7I POWER Azul   13S             Alvaro Rafael Pascual    mic015     microtec     05/03/22 0:00      12/03/22 0:00     Cancelado           C1      72490                      PUEBLA         PUE.   Heroica Puebla de Zaragoza               Puebla  ZALC610119MPLPRR07
2          5               37  1959.000000   490.00000        0.0   170.0        1469.00000  2210.000000               0.0     1.0       0          0               0.0               0       0    0.00           0     25.01             0.0      20.238285          58.0                         0  SZ7V3NZT  13/11/21 14:13       ZTE            BLADE A3 2020 Gris   13S   Sintia Verenice Tenorio Perez E   mic0437     microtec     05/03/22 0:00      12/03/22 0:00     Cancelado           C1      72490                    TANTOYUCA        VER.                            0                    0                   0
3          6               38  1959.000000   490.00000        0.0   170.0        1469.00000  2210.000000               0.0     2.0       0          0               0.0               0       0    0.00           0     25.01          7000.0      13.000000          42.0                         0  9I08UIQZ  13/11/21 15:45       ZTE            BLADE A3 2020 Gris   13S        Luz Aylin Hernandez Lopez1   mic0748     microtec     05/03/22 0:00      12/03/22 0:00          Mora           C1      72490                  AMXTLAN PUE        VER.                     Zacatlan               Puebla  SAMJ790115MPLNRS02
4          7               44  4299.000000  1075.00000        0.0   178.0        3224.00000  6942.000000               0.0     1.0       0          0               0.0               0       0    0.00           0     25.01          7000.0      20.238285          33.0                         0  JMF4LKYU  13/11/21 16:10  MOTOROLA                         G10 B   39S   Sintia Verenice Tenorio Perez E   mic0437     microtec     05/03/22 0:00      12/03/22 0:00          Mora           C1      72490                   TANTOYUCA         VER.                    Tantoyuca             Veracruz  TEHF880707HVZRRR07
...      ...              ...          ...         ...        ...     ...               ...          ...               ...     ...     ...        ...               ...             ...     ...     ...         ...       ...             ...            ...           ...                       ...       ...             ...       ...                           ... 

In [1709]:
data_clean['reautorizacion'].value_counts()

0    21961
1      774
Name: reautorizacion, dtype: int64

In [1710]:
numeric = res.select_dtypes(include=['number']).columns
df2 = res.dropna(subset=numeric)

In [1711]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20439 entries, 0 to 22734
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   folio                     20439 non-null  int64  
 1   folio_solicitud           20439 non-null  int64  
 2   precio                    20439 non-null  float64
 3   enganche                  20439 non-null  float64
 4   descuento                 20439 non-null  float64
 5   semana                    20439 non-null  float64
 6   monto_financiado          20439 non-null  float64
 7   costo_total               20439 non-null  float64
 8   monto_accesorios          20439 non-null  float64
 9   status                    20439 non-null  float64
 10  fraude                    20439 non-null  int64  
 11  inversion                 20439 non-null  int64  
 12  pagos_realizados          20439 non-null  float64
 13  reautorizacion            20439 non-null  int64  
 14  puntos

In [1712]:
df2

folio  folio_solicitud  precio  enganche  descuento  semana  monto_financiado  costo_total  monto_accesorios  status  fraude  inversion  pagos_realizados  reautorizacion  puntos  riesgo  score_buro  porc_eng  limite_credito  semana_actual  edad_cliente  status_cuenta_dicotomica       tag           fecha     marca                        modelo plazo                      agente_venta  dis_venta      empresa fecha_ultimo_pago fecha_pago_proximo status_cuenta razones_buro cp_cliente          cd_cliente edo_cliente                    cd_venta            edo_venta                curp
0          3               30  1949.0     780.0        0.0    81.0            1169.0       2106.0               0.0     2.0       0          0               0.0               0       0    0.00           0     40.02          5000.0           26.0          23.0                         0  HDNAWQ3A  12/11/21 19:00       ZTE            Blade A3 2020 RO B   26S   Sintia Verenice Tenorio Perez E    mic0437     microtec     05/03/22 0:00      12/03/22 0:00     Cancelado           C1      72490                   0           0                   Tantoyuca             Veracruz  AEVM980413MVZNDR02
1          4               33  2999.0    1050.0        0.0   225.0            1949.0       2925.0               0.0     2.0       0          0               0.0               0       0    0.00           0     35.01          6000.0           13.0          60.0                         0  M418YNR4  12/11/21 19:15  MOTOROLA  LTE XT2097-12 E7I POWER Azul   13S             Alvaro Rafael Pascual     mic015     microtec     05/03/22 0:00      12/03/22 0:00     Cancelado           C1      72490             PUEBLA         PUE.  Heroica Puebla de Zaragoza               Puebla  ZALC610119MPLPRR07
3          6               38  1959.0     490.0        0.0   170.0            1469.0       2210.0               0.0     2.0       0          0               0.0               0       0    0.00           0     25.01          7000.0           13.0          42.0                         0  9I08UIQZ  13/11/21 15:45       ZTE            BLADE A3 2020 Gris   13S        Luz Aylin Hernandez Lopez1    mic0748     microtec     05/03/22 0:00      12/03/22 0:00          Mora           C1      72490         AMXTLAN PUE        VER.                    Zacatlan               Puebla  SAMJ790115MPLNRS02
5          8               49  2999.0     750.0        0.0   156.0            2249.0       4056.0               0.0     2.0       0          0               0.0               0       0    0.00           0     25.01          7000.0           26.0          38.0                         0  FOBQ8A27  13/11/21 16:50  MOTOROLA  LTE XT2097-12 E7I POWER Azul   26S     Karim Hassan Mendez Animas GP    mic0569     microtec     03/09/22 0:00      06/12/22 0:00          Mora           C1      72490            PAPANTLA        VER.                    Papantla             Veracruz  FAAE830916MVZRRG00
6          9               50  2999.0     900.0        0.0   145.0            2099.0       3770.0               0.0     2.0       0          0               0.0               0       0    0.00           0     30.01          6000.0           26.0          21.0                         0  UND81DCF  13/11/21 17:19  MOTOROLA      E7I POWER 2+32 GB AZUL B   26S   Luis Gerardo Almanzar Hernandez    mic0437     microtec     03/09/22 0:00      06/12/22 0:00          Mora           C1      72490           TANTOYUCA        VER.                   Tantoyuca             Veracruz  JAPC000801HVZCRSA0
...      ...              ...     ...       ...        ...     ...               ...          ...               ...     ...     ...        ...               ...             ...     ...     ...         ...       ...             ...            ...           ...                       ...       ...             ...       ...                           ...   ...                               ...        ...          ...               ...                ...   

In [1713]:
df_coef = pd.DataFrame(columns=['Variable', 'Analisis', 'Precision', 'Exactitud','Sensibilidad'])

##Analizar 10 casos de correlación logística que existe entre diferentes variables de nuestra base de datos, aplicando la herramienta de “Regresión Logística”

###Analisis 1

In [1714]:
Vars_Indep= df2[['enganche', 'precio', 'descuento']]
Var_Dep= df2['status_cuenta_dicotomica']

In [1715]:
X= Vars_Indep
y= Var_Dep

In [1716]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1717]:
escalar = StandardScaler()

In [1718]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1719]:
algoritmo = LogisticRegression()

In [1720]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1721]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1722]:
y_pred = algoritmo.predict(X_test)
y_pred

array([1, 1, 1, ..., 0, 0, 0])

In [1723]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[2182  982]
 [1824 1144]]


In [1724]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.5413913466582816


In [1725]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.5375390597046967


In [1726]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.5289015052576417


In [1727]:
df_coef.loc[0] = ['status_cuenta_dicotomica', '1', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 2

In [1728]:
Vars_Indep= df2[['enganche', 'precio', 'limite_credito']]
Var_Dep= df2['puntos']

In [1729]:
X= Vars_Indep
y= Var_Dep

In [1730]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1731]:
escalar = StandardScaler()

In [1732]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1733]:
algoritmo = LogisticRegression()

In [1734]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1735]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1736]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [1737]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[5155  195]
 [ 291  491]]


In [1738]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.8311548637082449


In [1739]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.7957143198604106


In [1740]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.8119603284292396


In [1741]:
df_coef.loc[1] = ['puntos', '2', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 3

In [1742]:
Vars_Indep= df2[['enganche', 'precio', 'limite_credito']]
Var_Dep= df2['reautorizacion']

In [1743]:
df2['reautorizacion'].value_counts()

0    19720
1      719
Name: reautorizacion, dtype: int64

In [1744]:
X= Vars_Indep
y= Var_Dep

In [1745]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1746]:
escalar = StandardScaler()

In [1747]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1748]:
algoritmo = LogisticRegression()

In [1749]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1750]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1751]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [1752]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[5906    5]
 [ 221    0]]


In [1753]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.4819650726293455


In [1754]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.49957705971916766


In [1755]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.4906130586476159


In [1756]:
df_coef.loc[2] = ['reautorizacion', '3', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 4

In [1757]:
Vars_Indep= df2[['limite_credito', 'precio', 'monto_financiado']]
Var_Dep= df2['inversion']

In [1758]:
X= Vars_Indep
y= Var_Dep

In [1759]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1760]:
escalar = StandardScaler()

In [1761]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1762]:
algoritmo = LogisticRegression()

In [1763]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1764]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1765]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [1766]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[4686   13]
 [1430    3]]


In [1767]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.4768435251798561


In [1768]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.49966348202249977


In [1769]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.43535749462300743


In [1770]:
df_coef.loc[3] = ['inversion', '4', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 5

In [1771]:
Vars_Indep= df2[['costo_total', 'monto_financiado', 'precio']]
Var_Dep= df2['fraude']

In [1772]:
X= Vars_Indep
y= Var_Dep

In [1773]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1774]:
escalar = StandardScaler()

In [1775]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1776]:
algoritmo = LogisticRegression()

In [1777]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1778]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1779]:
y_pred = algoritmo.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [1780]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[5659    0]
 [ 473    0]]


In [1781]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.4614318330071755


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1782]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.5


In [1783]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.4799423288949199


In [1784]:
df_coef.loc[4] = ['fraude', '5', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 6

In [1785]:
Vars_Indep= df2[['monto_financiado', 'costo_total', 'descuento']]
Var_Dep= df2['empresa']

In [1786]:
X= Vars_Indep
y= Var_Dep

In [1787]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1788]:
escalar = StandardScaler()

In [1789]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1790]:
algoritmo = LogisticRegression()

In [1791]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1792]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1793]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['microtec', 'servicel', 'servicel', ..., 'servicel', 'microtec',
       'servicel'], dtype=object)

In [1794]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [1795]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.03142817707736306


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1796]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.03802717863801541


In [1797]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.03332515157277959


In [1798]:
df_coef.loc[5] = ['empresa', '6', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 7

In [1799]:
Vars_Indep= df2[['costo_total', 'precio', 'limite_credito']]
Var_Dep= df2['marca']

In [1800]:
X= Vars_Indep
y= Var_Dep

In [1801]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1802]:
escalar = StandardScaler()

In [1803]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1804]:
algoritmo = LogisticRegression()

In [1805]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1806]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1807]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Samsung', 'ZTE', 'Samsung', ..., 'Samsung', 'Samsung', 'ZTE'],
      dtype=object)

In [1808]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    19    0    1    0    0    0   30]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    11    0    0    0    0    0   10]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    43    0    2    0    0    0   34]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    84    0    0    0    0    0   23]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    1]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     5    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     3    0    0    0    0    0   19]
 [   0    0    0    0    0    0    0    1    0    0    0    0    0    0
   773    0    0    0    0    0    1]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
   446    0    0    0    0 

In [1809]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.07475322498002855


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1810]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.08651042243788216


In [1811]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.06404904928225774


In [1812]:
df_coef.loc[6] = ['marca', '7', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 8

In [1813]:
Vars_Indep= df2[['enganche', 'precio', 'costo_total']]
Var_Dep= df2['modelo']

In [1814]:
X= Vars_Indep
y= Var_Dep

In [1815]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1816]:
escalar = StandardScaler()

In [1817]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1818]:
algoritmo = LogisticRegression()

In [1819]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1820]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1821]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['A03', 'A13', 'A04E', ..., 'A03', 'A03', 'A03s'], dtype=object)

In [1822]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [1823]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.00814990394678218


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1824]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.0169035415995843


In [1825]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.009889860445606632


In [1826]:
df_coef.loc[7] = ['modelo', '8', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 9

In [1827]:
Vars_Indep= df2[['porc_eng', 'precio', 'limite_credito']]
Var_Dep= df2['edo_venta']

In [1828]:
X= Vars_Indep
y= Var_Dep

In [1829]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1830]:
escalar = StandardScaler()

In [1831]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1832]:
algoritmo = LogisticRegression()

In [1833]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1834]:
algoritmo.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [1835]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Puebla', 'Yucatan', 'Puebla', ..., 'Yucatan', 'Puebla', 'Yucatan'],
      dtype=object)

In [1836]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    1
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   13    0    0    0    0    0    0    0    0    3
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    1
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   39    0    0    0    0    0    0    0    0   66
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   45    0    0    0    0    0    0    0    0  122
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0   20    0    0    0    0    0    0    0    0   35
     0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0 

In [1837]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.0356160830073634


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1838]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.0457614103787741


In [1839]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.03164945457371617


In [1840]:
df_coef.loc[8] = ['edo_venta', '9', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

###Analisis 10

In [1841]:
Vars_Indep= df2[['enganche', 'precio', 'edad_cliente']]
Var_Dep= df2['status_cuenta']

In [1842]:
X= Vars_Indep
y= Var_Dep

In [1843]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [1844]:
escalar = StandardScaler()

In [1845]:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [1846]:
algoritmo = LogisticRegression()

In [1847]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1848]:
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [1849]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['Corriente', 'Corriente', 'Corriente', ..., 'Corriente',
       'Corriente', 'Corriente'], dtype=object)

In [1850]:
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[   0    0  972    0    8]
 [   0    0   22    0    0]
 [   0    0 2950    0   17]
 [   0    0  518    0    4]
 [   0    0 1626    0   15]]


In [1851]:
precision = precision_score(y_test, y_pred, average="macro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.1650937761318839


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [1852]:
sensibilidad = recall_score(y_test, y_pred, average="macro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.2006822149063218


In [1853]:
puntajef1 = f1_score(y_test, y_pred, average="macro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.13387557409631545


In [1854]:
df_coef.loc[9] = ['status_cuenta', '10', round(precision,2), round(sensibilidad,2), round(puntajef1,2) ]

##Realizar una tabla de todos los coeficientes de precisión, exactitud y sensibilidad obtenidos para cada correlación analizada, según sea el caso.

### Coeficientes de precisión, exactitud y sensibilidad :

In [1856]:
df_coef

Variable Analisis  Precision  Exactitud  Sensibilidad
0  status_cuenta_dicotomica        1       0.54       0.54          0.53
1                    puntos        2       0.83       0.80          0.81
2            reautorizacion        3       0.48       0.50          0.49
3                 inversion        4       0.48       0.50          0.44
4                    fraude        5       0.46       0.50          0.48
5                   empresa        6       0.03       0.04          0.03
6                     marca        7       0.07       0.09          0.06
7                    modelo        8       0.01       0.02          0.01
8                 edo_venta        9       0.04       0.05          0.03
9             status_cuenta       10       0.17       0.20          0.13